OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Patient #org1
    Domain: patient.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: GovtHos #org2
    Domain: govthos.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: PHC #org3
    Domain: phc.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: PvtHos  #org4
    Domain: pvthos.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1 
  - Name: Research  #org5
    Domain: research.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1       
  - Name: Insurance   #org6
    Domain: insurance.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1      