NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.phc.example.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.phc.example.com-cert.pem
    OrganizationalUnitIdentifier: peer
